server:
  port: 8761
  
spring:
  application:
    name: service-registry
    
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 2